apiVersion: node.waok8s.github.io/v1beta1
kind: NodeConfig
metadata:
  name: nodeconfig-sample
  namespace: wao-system
spec:
  nodeName: worker-0
  metricsCollector:
    inletTemp:
      type: Redfish
      endpoint: "https://10.0.0.1"
      basicAuthSecret:
        name: "worker-0-redfish-basicauth"
      fetchInterval: 10s
    deltaP:
      type: DifferentialPressureAPI
      endpoint: "http://10.0.0.1:5000"
      fetchInterval: 10s
  predictor:
    powerConsumption:
      type: V2InferenceProtocol
      endpoint: "http://10.0.0.1:8080/v2/models/myModel/versions/v0.1.0/infer"
    # powerConsumptionEndpointProvider:
    #   type: Redfish
    #   endpoint: "https://10.0.0.1"
    #   basicAuthSecret:
    #     name: "worker-0-redfish-basicauth"
